spring.application.name=reto-a

# H2 en memoria para ejecucion y pruebas
spring.datasource.url=jdbc:h2:mem:retodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true

# Consola H2 (util para explorar el esquema durante la auditoría)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080
