CREATE TABLE IF NOT EXISTS saldos_mensuales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    afiliadoId VARCHAR(50) NOT NULL,
    mes VARCHAR(7) NOT NULL,
    total NUMERIC(19,4) NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_saldos_afiliado_mes UNIQUE (afiliadoId, mes)
);

CREATE TABLE IF NOT EXISTS aportes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    afiliadoId VARCHAR(50) NOT NULL,
    monto NUMERIC(19,4) NOT NULL,
    fecha DATE NOT NULL,
    canal VARCHAR(50) NOT NULL,
    periodo VARCHAR(7) NOT NULL,
    marcadaRevision BOOLEAN NOT NULL DEFAULT FALSE,
    idempotenciaKey VARCHAR(100) NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_aportes_afiliado_periodo ON aportes(afiliadoId, periodo);
CREATE INDEX IF NOT EXISTS idx_aportes_idempotencia ON aportes(idempotenciaKey);